/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy): 24. 7.2019   Time (hh:mm): 16:52                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_BTN_INC_SELECTED 25
#define GX_COLOR_ID_BTN_INC_NORMAL 26
#define GX_COLOR_ID_BTN_DEC_NORMAL 27
#define GX_COLOR_ID_BTN_DEC_SELECTED 28
#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_ABOUT_NORMAL2 5
#define GX_PIXELMAP_ID_ABOUT_SELECTED2 6
#define GX_PIXELMAP_ID_CESEQ_PROYECTO 7
#define GX_PIXELMAP_ID_CLOSE_NORMAL2 8
#define GX_PIXELMAP_ID_CLOSE_SELECTED2 9
#define GX_PIXELMAP_ID_FONDOCIAN 10
#define GX_PIXELMAP_ID_VENTILADOR1 11
#define GX_PIXELMAP_ID_VENTILADOR2 12
#define GX_PIXELMAP_ID_VENTILADOR3 13
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 14

/* String Ids                                                                  */

#define GX_STRING_ID_LBL_START 1
#define GX_STRING_ID_LBL_INFO_DUTY_CYCLE 2
#define GX_STRING_ID_LBL_INFO_SPEED 3
#define GX_STRING_ID_LBL_INFO_SET_POINT 4
#define GX_STRING_ID_LBL_STOP 5
#define GX_STRING_ID_LBL_INC 6
#define GX_STRING_ID_LBL_DEC 7
#define GX_STRING_ID_LBL_INFO_DEV 8
#define GX_STRING_ID_LBL_INFO_VER 9
#define GX_STRING_ID_STRING_1 10
#define DISPLAY_1_STRING_TABLE_SIZE 11

#endif                                       /* sentry                         */
